---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: ubuntu/trusty64
      network:
      - ["private_network", {ip: "192.168.34.33"}]
      customize:
        memory: 4096
        cpus: 8

suites:
  - name: default
    run_list:
    - recipe[chef-server12::default]
    attributes:
